=== lootfold-humber/js-xml/catalog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="colors">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="color" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sizes" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="size" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="images" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="image" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="filename">
                                                        <xs:attribute name="name" type="xs:string" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="thumbnail" type="filename" minOccurs="0" />
                        </xs:all>
                        <xs:attribute name="sku" type="xs:positiveInteger" use="required" />
                        <xs:attribute name="category" type="xs:string" use="required" />
                        <xs:attribute name="isFeatured" type="yesno" use="required" />
                        <xs:attribute name="price" type="price" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="yesno">
        <xs:restriction base="xs:token">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="price">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+.\d{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="filename">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9-]+.(png|jpg|jpeg)"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== lootfold-humber/js-xml/catalog.xml
<?xml version="1.0" encoding="utf-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog.xsd">
  <product sku="29043" category="audio" isFeatured="no" price="219.99">
    <name>Sennheiser PC350 Gaming Stereo Headset</name>
    <description>Gaming stereo headset, 10-26000Hz, 150ohm, 10-ft cord, noise-cancelling microphone.</description>
    <colors>
      <color>Black</color>
      <color>Red</color>
    </colors>
  </product>
  <product sku="57134" category="appliance" isFeatured="yes" price="459.99">
    <name>Whirlpool Energy Saver Washer</name>
    <thumbnail>washer-thumb.png</thumbnail>
    <images>
      <image name="Front View of washer">washer-front.jpg</image>
      <image name="Washer controls">washer-controls.jpg</image>
    </images>
    <description>Front-loading washer from Whirlpool helps save money</description>
    <sizes>
      <size>3.9 cubic feet</size>
    </sizes>
    <colors>
      <color>White</color>
      <color>Silver</color>
    </colors>
  </product>
</catalog>
